services:
  db:
    image: postgres:17.5
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: creditos
    ports:
      - "5432:5432"
    volumes:
      - pgdata17:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev"]
      interval: 10s
      retries: 5

volumes:
  pgdata17:
